name: Build APK

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Website URL'
        required: true
      userId:
        description: 'User ID'
        required: true
      appName:
        description: 'App Name'
        required: true
      buildId:
        description: 'Build ID'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Flutter WebView template
        uses: actions/checkout@v4
        with:
          repository: '${{ github.repository_owner }}/flutter_webview_template'
          path: template
          
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'

      - name: Customize Template
        run: |
          cd template
          
          # Update the app name in pubspec.yaml
          sed -i "s/name: webview_flutter/name: ${{ github.event.inputs.appName }}/g" pubspec.yaml
          
          # Update the website URL in the main.dart file
          sed -i "s|https://example.com|${{ github.event.inputs.url }}|g" lib/main.dart
          
          # Update the app display name in Android
          sed -i "s/WaterWise/${{ github.event.inputs.appName }}/g" android/app/src/main/AndroidManifest.xml
          
          # Get dependencies
          flutter pub get

      - name: Build APK
        run: |
          cd template
          flutter build apk --release

      - name: Setup Firebase
        uses: w9jds/firebase-action@v11.16.0
        with:
          args: app:create --project ${{ secrets.FIREBASE_PROJECT_ID }} android ${{ github.event.inputs.appName }}
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

      - name: Upload to Firebase Storage
        uses: w9jds/firebase-action@v11.16.0
        with:
          args: storage:upload template/build/app/outputs/flutter-apk/app-release.apk --project ${{ secrets.FIREBASE_PROJECT_ID }} --public
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

      - name: Get download URL
        id: get_url
        uses: w9jds/firebase-action@v11.16.0
        with:
          args: storage:url gs://${{ secrets.FIREBASE_STORAGE_BUCKET }}/${{ github.event.inputs.userId }}/apps/${{ github.event.inputs.buildId }}/app-release.apk --project ${{ secrets.FIREBASE_PROJECT_ID }}
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

      - name: Update Firestore build record
        uses: w9jds/firebase-action@v11.16.0
        with:
          args: firestore:update builds/${{ github.event.inputs.buildId }} --project ${{ secrets.FIREBASE_PROJECT_ID }} --data '{"status":"completed","downloadUrl":"${{ steps.get_url.outputs.result }}"}'
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }} 